name: RFM Analysis CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Format code with Black
      run: |
        pip install black
        black .
        
    - name: Check for code changes after formatting
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "⚠️ Code was reformatted. Consider running Black locally before pushing."
          git status
        else
          echo "✅ Code formatting is correct."
        fi
        
    - name: Run test file structure
      run: |
        # Simple test to check if essential modules exist
        python -c "import os; assert os.path.isdir('src'), 'src directory missing'"
        python -c "import os; assert os.path.exists('src/rfm_analysis.py'), 'rfm_analysis.py missing'"
